# Pytorch Operations

## Tensor

- 다차원 Array를 표현하는 pytorch 클래스
- 사실상 numpy의 ndarray와 동일
- tensor를 생성하는 함수도 거의 동일

In [1]:
# numpy
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [5]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [7]:
# array to tensor

data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [8]:
# ndarray to tensor
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

실제로는 직접 텐서를 생성해서 사용하는 경우는 별로 없다.

기본적으로 tensor가 가질 수 있는 data타입은 numpy와 동일

In [15]:
data = [[3,5,20],[10,5,50],[1,5,10]]
x_data = torch.tensor(data)
print(x_data[1:])
print(x_data[:2,1:])
print(x_data.flatten())
print(torch.ones_like(x_data))
print(x_data.numpy())
print(x_data.shape)
print(x_data.dtype)

tensor([[10,  5, 50],
        [ 1,  5, 10]])
tensor([[ 5, 20],
        [ 5, 50]])
tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
[[ 3  5 20]
 [10  5 50]
 [ 1  5 10]]
torch.Size([3, 3])
torch.int64


In [18]:
x_data.device #데이터가 cpu에 올라있는지, gpu에 올라있는지

device(type='cpu')

### view - reshape

In [38]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.2265, 0.2143],
         [0.0105, 0.9151],
         [0.8252, 0.4267]],

        [[0.8114, 0.3935],
         [0.7828, 0.1282],
         [0.0701, 0.3265]]])

In [39]:
tensor_ex.view(-1,6)

tensor([[0.2265, 0.2143, 0.0105, 0.9151, 0.8252, 0.4267],
        [0.8114, 0.3935, 0.7828, 0.1282, 0.0701, 0.3265]])

In [40]:
tensor_ex.reshape(-1,6)

tensor([[0.2265, 0.2143, 0.0105, 0.9151, 0.8252, 0.4267],
        [0.8114, 0.3935, 0.7828, 0.1282, 0.0701, 0.3265]])

In [41]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [42]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [43]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

view : 기존의 메모리 주소를 참조하여 모양만 변경

In [44]:
a = torch.zeros(3,2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [45]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [46]:
b

tensor([0., 0., 0., 0., 0., 0.])

### squeeze, unsqueeze

- squeeze : 차원감소
- unsqueeze : 차원증가

In [62]:
a = torch.rand(size=(2,1,2))
print(a)
print(a.squeeze())

tensor([[[0.7173, 0.2984]],

        [[0.9330, 0.8644]]])
tensor([[0.7173, 0.2984],
        [0.9330, 0.8644]])


In [63]:
a = torch.rand(size=(2,2))
print(a.unsqueeze(0))
print(a.unsqueeze(0).shape)

tensor([[[0.7027, 0.1725],
         [0.3307, 0.9557]]])
torch.Size([1, 2, 2])


In [64]:
print(a.unsqueeze(1))
print(a.unsqueeze(1).shape)

tensor([[[0.7027, 0.1725]],

        [[0.3307, 0.9557]]])
torch.Size([2, 1, 2])


In [65]:
print(a.unsqueeze(2))
print(a.unsqueeze(2).shape)

tensor([[[0.7027],
         [0.1725]],

        [[0.3307],
         [0.9557]]])
torch.Size([2, 2, 1])


### dot - mm

- dot : 벡터 - 벡터 연산
- mm : 행렬 - 행렬 연산
- matmul : 행렬 연산(+ 자동 브로드캐스팅)

In [77]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.mm(b)

RuntimeError: self must be a matrix

In [78]:
a = torch.rand(5,2,3) # 5 = batch
b = torch.rand(3)
a.matmul(b)

tensor([[0.0497, 0.4199],
        [0.0628, 0.1075],
        [0.1339, 0.0783],
        [0.2211, 0.4202],
        [0.0274, 0.0532]])

In [80]:
print(a[0].mm(torch.unsqueeze(b,1)))
print(a[1].mm(torch.unsqueeze(b,1)))
print(a[2].mm(torch.unsqueeze(b,1)))
print(a[3].mm(torch.unsqueeze(b,1)))
print(a[4].mm(torch.unsqueeze(b,1)))

tensor([[0.0497],
        [0.4199]])
tensor([[0.0628],
        [0.1075]])
tensor([[0.1339],
        [0.0783]])
tensor([[0.2211],
        [0.4202]])
tensor([[0.0274],
        [0.0532]])


## mldl formula

### nn.functional

In [83]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [85]:
y = torch.randint(5,(10,5))
y_label = y.argmax(dim=1)
y_label

tensor([0, 3, 0, 3, 3, 0, 0, 4, 0, 4])

In [86]:
torch.nn.functional.one_hot(y_label)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1]])

### AutoGrad

pytorch의 핵심은 자동미분 지원 

In [82]:
w = torch.tensor(2.0, requires_grad = True)
y = w**2
z = 10*y + 25
z.backward()
w.grad

tensor(40.)

In [89]:
#편미분 
a = torch.tensor([2.,3.],requires_grad=True)
b = torch.tensor([6.,4.],requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1,1])
Q.backward(gradient=external_grad)

In [90]:
a.grad

tensor([36., 81.])

In [91]:
b.grad

tensor([-12.,  -8.])